// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yiafjmmlzqmakhqdklyo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlpYWZqbW1senFtYWtocWRrbHlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMjg4NjMsImV4cCI6MjA3MTcwNDg2M30.ktMpG0Gm2aKy3MWk4HJo6DdNuhrMsb7N4ZnDc4d51pc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});